version: '3'

services:
  selenium:
    build:
      context: .
    volumes:
        - ${APP_DIR}:/app
        - ${CACHE_DIR}:/app/cache
  dev:
    build:
      context: .
    volumes:
        - ${APP_DIR}:/app
        - ${CACHE_DIR}:/app/cache
    tty: true
