version: '3'

services:
  selenium:
    build:
      context: .
    volumes:
        - ${APP_DIR}:/app
        - ${CACHE_DIR}:/app/cache
  server:
    build:
      context: .
    volumes:
        - ${APP_DIR}:/app
        - ${CACHE_DIR}:/app/cache
    environment:
      - REQUEST_HANDLER=${REQUEST_HANDLER}
    tty: true
    ports:
      - "${SERVER_PORT}:3000"
    command: python server.py
