version: '3.6'

services:
  selenium:
    container_name: selenium-app
    build:
      context: .
    volumes:
        - ${APP_DIR}:/app
        - ${CACHE_DIR}:/app/cache
  server:
    container_name: ${SERVER_NAME}
    build:
      context: .
    volumes:
        - ${APP_DIR}:/app
        - ${CACHE_DIR}:/app/cache
    tty: true
    ports:
      - "${SERVER_PORT}:80"
    command: python server.py
    networks:
      - default
      - external
  dev-server:
        container_name: ${SERVER_NAME}
        build:
          context: .
        volumes:
            - ${APP_DIR}:/app
            - ${CACHE_DIR}:/app/cache
        tty: true
        ports:
          - "${SERVER_PORT}:80"
        networks:
          - default
          - external

networks:
  external:
    name: ${EXTERNAL_NETWORK}
    external: true
