version: '3'

services:
  selenium:
    build:
      context: .
    volumes:
        - ${APP_DIR}:/app
        - ${CACHE_DIR}:/app/cache
  server:
    build:
      context: .
    volumes:
        - ${APP_DIR}:/app
        - ${CACHE_DIR}:/app/cache
    tty: true
    ports:
      - "${SERVER_PORT}:3000"
    command: python server.py
    networks:
      - default
      - external

networks:
  external:
    name: ${EXTERNAL_NETWORK}
    external: true
