version: '3.6'

services:
  app:
    build:
      context: .
    environment:
      - USER_SESSION_DIR=${USER_SESSION_DIR}
    volumes:
        - ${APP_DIR}:/app
        - ${CACHE_DIR}:${USER_SESSION_DIR}
    tty: true
